More bash compatability
I will not test bash further because screw that

diff --git a/scripts/make-tmux-escaped-binary b/scripts/make-tmux-escaped-binary
--- a/scripts/make-tmux-escaped-binary
+++ b/scripts/make-tmux-escaped-binary
@@ -1,49 +1,54 @@
 #!/bin/zsh
+#TODO: make this not zsh-specific so the intention of being zsh/bash is possible
 
-src_dir="${SRC_DIR:-$(dirname $(realpath $0))}"
-out_dir="${OUT_DIR:-"$src_dir/bin"}"
-mkdir -p "$out_dir"
-compilers=(g++ clang++)
-if [[ -z $CXX ]]; then
-  for c in ${compilers[@]}; do
-    if command -v "$c" >/dev/null 2>&1; then
-      CXX="$c"
-      break
-    fi
-  done
-fi
-if [[ -z $CXX ]]; then
-  echo "Error: No C++ compiler found (searched ${compilers[@]})"
-  exit 1
-fi
-
-function main() {
-  local program=$1
-
-  function c_quoted_args() {
-    local result=""
-    for arg in "$@"; do
-      # Escape any quotes and add double quotes around each argument
-      result+='"'"${arg//\"/\\\"}"'"',
+function __do_make_tmux_wrappers() {
+  local src_dir="${SRC_DIR:-$(dirname $(realpath $0))}"
+  local out_dir="${OUT_DIR:-"$src_dir/bin"}"
+  mkdir -p "$out_dir"
+  local compilers=(g++ clang++)
+  if [[ -z $CXX ]]; then
+    for c in "${compilers[@]}"; do
+      if command -v "$c" >/dev/null 2>&1; then
+        CXX="$c"
+        break
+      fi
     done
+  fi
+  if [[ -z $CXX ]]; then
+    echo "Error: No C++ compiler found (searched ${compilers[@]})"
+    exit 1
+  fi
 
-    result=${result%,}
+  function __do_make_tmux_wrapper() {
+    local program=$1
+    local program_uppercase=$(echo "$program" | tr '[:lower:]' '[:upper:]')
 
-    # Output the result
-    echo "$result"
+    function c_quoted_args() {
+      local result=""
+      for arg in "$@"; do
+        # Escape any quotes and add double quotes around each argument
+        result+='"'"${arg//\"/\\\"}"'"',
+      done
+
+      result=${result%,}
+
+      echo "$result"
+    }
+
+    function increment_tmux_counter_cmd() {
+      local op=$1
+      c_quoted_args '$_TMUX_REAL_PATH' set -pFt '$TMUX_PANE' @escape_nav_keys "#{e|${op}:#{@escape_nav_keys},1}"
+    }
+
+    $CXX -O2 "$src_dir"/wrap.cpp -o "$out_dir/$program" \
+      -DPROGRAM="\$_${program_uppercase}_REAL_PATH" \
+      -DBEFORE_CMD="$(increment_tmux_counter_cmd +)" \
+      -DAFTER_CMD="$(increment_tmux_counter_cmd -)" \
+      -DBALANCED \
+      # -DDEBUG
   }
 
-  function increment_tmux_counter_cmd() {
-    local op=$1
-    c_quoted_args '$_TMUX_REAL_PATH' set -pFt '$TMUX_PANE' @escape_nav_keys "#{e|${op}:#{@escape_nav_keys},1}"
-  }
-
-  $CXX -O2 "$src_dir"/wrap.cpp -o "$out_dir/$program" \
-    -DPROGRAM="\$_${(U)program}_REAL_PATH" \
-    -DBEFORE_CMD="$(increment_tmux_counter_cmd +)" \
-    -DAFTER_CMD="$(increment_tmux_counter_cmd -)" \
-    -DBALANCED \
-    # -DDEBUG
+  for prog in "$@"; do __do_make_tmux_wrapper "$prog"; done
 }
 
-for prog in "$@"; do main "$prog"; done
+__do_make_tmux_wrappers "$@"
diff --git a/scripts/setup-wrappers b/scripts/setup-wrappers
--- a/scripts/setup-wrappers
+++ b/scripts/setup-wrappers
@@ -8,7 +8,7 @@ fi
 if [[ $_TMUX_ESCAPE_NAV_ENABLED = 1 && -z $_TMUX_ESCAPE_NAV_SETUP ]]; then
   __configure_tmux_wrappers() {
     # Allow user to specify TMUX_ESCAPED_PROGRAMS as a *space-separated* list (so that it can be portably read in keys.sh as well)
-    if [[ ! -v TMUX_ESCAPED_PROGRAMS ]]; then
+    if [[ -z ${TMUX_ESCAPED_PROGRAMS+x} ]]; then
       export TMUX_ESCAPED_PROGRAMS="fzf nvim"
     fi
     if [[ -z $TMUX_ESCAPED_PROGRAMS ]]; then
@@ -30,16 +30,26 @@ if [[ $_TMUX_ESCAPE_NAV_ENABLED = 1 && -z $_TMUX_ESCAPE_NAV_SETUP ]]; then
     local out_dir="$src_dir/bin"
 
     local tmux_path=$(command -v tmux 2>/dev/null)
-    [[ -n "$tmux_path" ]] || { >&2 echo "Failed to find _TMUX_REAL_PATH, cannot create wrappers"; return 1 }
+    if [[ ! -x "$tmux_path" ]]; then
+      >&2 echo "Failed to find _TMUX_REAL_PATH, cannot create wrappers"; return 1
+    fi
     export _TMUX_REAL_PATH="$tmux_path"
+
+    local do_source=source
+    if command -v source_compile >/dev/null 2>&1; then
+      do_source=source_compile
+    fi
 
     for cmd_name in $(echo $TMUX_ESCAPED_PROGRAMS); do
       if [[ ! -f "$out_dir/$cmd_name" ]]; then
         >&2 echo "Compiling tmux wrapper for $cmd_name..."
-        SRC_DIR="$src_dir" OUT_DIR="$out_dir" "$script_dir/make-tmux-escaped-binary" "$cmd_name" || return 1
+        SRC_DIR="$src_dir" OUT_DIR="$out_dir" "$do_source" "$script_dir/make-tmux-escaped-binary" "$cmd_name" || return 1
       fi
       local cmd_path=$(command -v "$cmd_name" 2>/dev/null)
-      [[ -n "$cmd_path" ]] || { >&2 echo "Failed to find real path for $cmd_name, cannot create wrapper" }
+      if [[ ! -x "$cmd_path" ]]; then
+        >&2 echo "Failed to find real path for $cmd_name, cannot create wrapper"
+        continue
+      fi
       if [[ -n "$cmd_path" ]]; then
         local upper_cmd_name=$(printf "%s" "$cmd_name" | tr '[:lower:]' '[:upper:]')
         export "_${upper_cmd_name}_REAL_PATH=$cmd_path"
